### ISSUE TITLE
Suggestion: Possibility to add multiple breakpoints

### ISSUE THREAD

**Issue by COD3BREAK3R** [P0u4a/vs-gradient-maker#1]
Good extension, I wish it had the ability to add, remove breakpoints and change their position, that would be great, thank you!

**Comment by P0u4a** [comment]
Hi @COD3BREAK3R, thank you so much for the feedback! I will definitely look into implementing breakpoints once I have some free time on my hands. In the meantime, feel free to contribute to the project as well if you like :)

**Comment by P0u4a** [comment]
Currently wondering whether there should be some limit on the number of breakpoints the user can generate.
