### ISSUE TITLE
More formats for color values

### ISSUE THREAD

**Issue by fbongcam** [P0u4a/vs-gradient-maker#2]
Great tool and exactly what I was looking for.

Need ability to change what format the color values should be written in, RGB, HSL for example. Maybe RGBA for transparency?

This and the added breakpoints as mentioned in [issue#1](https://github.com/P0u4a/vs-gradient-maker/issues/1) would increase the usability a lot.

**Comment by P0u4a** [comment]
Hey @fbongcam, thanks for the feature request! 
Just to clarify, by color values, do you mean the values in the generated CSS code?

**Comment by fbongcam** [comment]
@P0u4a Yes exactly, generated CSS. RGBA would be useful if you added transparency options for example.
